# fly.toml app configuration file generated for datingappro on 2024-01-05T22:06:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingappro"
primary_region = "otp"

[build]
  image = "florindeveloperul/datingappro:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__CloudName = "dwrxiinj1"
  CloudinarySettings__ApiKey = "294818672675352"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
